#docker-compose-http3-tr.yml
version: '3.9'
services:
  caddy:
    image: caddy:latest
    volumes:
      - ./Caddyfile-http3-ha:/etc/caddy/Caddyfile
    restart: unless-stopped
  traefik:
    image: traefik:latest
    volumes:
      - ./traefik.yml:/etc/traefik/traefik.yml
      - ./traefik_dynamic.yml:/etc/traefik/traefik_dynamic.yml
      - ./localhost+1-key.pem:/etc/traefik/localhost+1-key.pem
      - ./localhost+1.pem:/etc/traefik/localhost+1.pem
      - ./localhost+1.pem:/etc/ssl/certs/localhost+1.pem
    ports:
      - 80:80
      - 443:443
      - "443:443/udp"
    restart: unless-stopped