version: '3'
services:
  service1:
    image: caddy
    volumes:
      - ./Caddyfile-traffic1:/etc/caddy/Caddyfile

  service2:
    image: caddy
    volumes:
      - ./Caddyfile-traffic2:/etc/caddy/Caddyfile

  caddy:
    image: caddy
    volumes:
      - ./Caddyfile-lb:/etc/caddy/Caddyfile
    ports:
      - 80:80
    restart: unless-stopped

