#docker-compose-http3-ha.yml
version: '3.9'
services:
  caddy:
    image: caddy:latest
    volumes:
      - ./Caddyfile-http3-ha:/etc/caddy/Caddyfile
    restart: unless-stopped
  haproxy:
    image: iuridiniz/haproxy:2.7.3
    volumes:
      - ./haproxy.cfg:/etc/haproxy/haproxy.cfg
      - ./localhost.pem:/etc/haproxy/certs/localhost.pem
    ports:
      - 80:80
      - 443:443
      - "443:443/udp"
    restart: unless-stopped