#docker-compose-http3.yml
version: '3.9'
services:
  api:
    build: .
    ports:
      - 8080:8080
  caddy:
    image: caddy:latest
    volumes:
      - ./Caddyfile-http3:/etc/caddy/Caddyfile
      - ./static:/var/www/html
    ports:
      - 80:80
      - 443:443
      - "443:443/udp"
    restart: unless-stopped