version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ca.pem:/var/nginx/ca.pem:ro
      - ./server.key:/var/nginx/server.key:ro
      - ./server.crt:/var/nginx/server.crt:ro

  go-service:
    build:
      context: .
      dockerfile: Dockerfile
