http:
  routers:
    dashboard:
      rule: "PathPrefix(`/api`) || PathPrefix(`/dashboard`)"
      entrypoints:
        - "web"
      service: "api@internal"
    myservice:
      rule: "Host(`localhost`)"
      service: myservice
      entrypoints:
        - "websecure"
      tls:
        domains:
          - main: "localhost"
  services:
    myservice:
      loadBalancer:
        healthcheck:
          path: "/"
          interval: "10s"
          timeout: "1s"
        servers:
          - url: "http://service1:80"
          - url: "http://service2:80"

tls:
  certificates:
    - certFile: "/etc/traefik/localhost+1.pem"
      keyFile: "/etc/traefik/localhost+1-key.pem"