experimental:
  http3: true

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"
    http3:
      advertisedPort: "443"

api:
  dashboard: true

providers:
  file:
    filename: "/etc/traefik/traefik_dynamic.yml"

log:
  level: TRACE