version: '3.9'
services:
  api:
    build: api
    ports:
      - "8081:8081"
    depends_on:
      - db
  frontend:
    build: frontend
    ports:
      - "3000:3000"
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    volumes:
      - ./.db:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql

