#docker-compose-http3.yml
version: '3.9'
services:
  caddy:
    image: caddy:latest
    volumes:
      - ./Caddyfile-http3:/etc/caddy/Caddyfile
    ports:
      - 80:80
      - 443:443
      - "443:443/udp"
    restart: unless-stopped