version: '3'
services:
  service1:
    image: caddy
    volumes:
      - ./Caddyfile-traffic1:/etc/caddy/Caddyfile

  service2:
    image: caddy
    volumes:
      - ./Caddyfile-traffic2:/etc/caddy/Caddyfile

  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 7070:7070
    restart: unless-stopped

